### ISSUE TITLE
Security Issues: No feedback TOKEN SESSION

### ISSUE THREAD

**Issue by samuel-prz** [adrianv99/Workingfy#2]
No se puede verificar la veracidad del usuario. Con solo la variable almacenada en el frontend(F12 > Application > Session Storage), el usuario podrá acceder a datos protegidos.

Pero para eso debe estar creada una sesión en el lado del servidor: 
A la hora que un usuario se valide, un Token único se debe generar y  así enviarlo al Frontend para que en cada solicitud futura hacer match con el Token de la sesión del lado del Servidor.

Hay diferentes librerias para sesiones en Node:
https://devcode.la/tutoriales/como-configurar-sesiones-en-expressjs/

A este feedback, se le debe agregar: JWT para la encriptacion de los datos entre el servidor y el cliente.

**Comment by adrianv99** [comment]
se puede verificar la veracidad del usuario con un token generado a base del id del usuario, su roll y una clave de sistema
